import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

export const defaultWranglerConfigPath = "wrangler.jsonc";
export const localWranglerConfigPath = "wrangler.local.jsonc";
export const generatedWranglerConfigPath = ".wrangler/generated/wrangler.jsonc";

interface WranglerConfigOptions {
	appEnv?: string;
	appName?: string;
	compatibilityDate?: string;
	databaseId?: string;
	databaseName?: string;
	outFile?: string;
	previewDatabaseId?: string;
	previewUrls?: boolean;
	workerName?: string;
	workersDev?: boolean;
}

function clean(value: string | undefined) {
	const trimmed = value?.trim();
	return trimmed && trimmed.length > 0 ? trimmed : undefined;
}

function readBoolean(value: string | undefined, fallback: boolean) {
	const normalized = clean(value)?.toLowerCase();

	if (!normalized) {
		return fallback;
	}

	if (["1", "true", "yes", "on"].includes(normalized)) {
		return true;
	}

	if (["0", "false", "no", "off"].includes(normalized)) {
		return false;
	}

	throw new Error(`Invalid boolean value: ${value}`);
}

export function resolveWranglerConfigPath() {
	const explicitConfig = clean(process.env.WRANGLER_CONFIG);

	if (explicitConfig) {
		return explicitConfig;
	}

	if (existsSync(localWranglerConfigPath)) {
		return localWranglerConfigPath;
	}

	return defaultWranglerConfigPath;
}

export function readWranglerConfigOptionsFromEnv(
	env: Record<string, string | undefined> = process.env,
): WranglerConfigOptions {
	const databaseId = clean(env.MAIL_BIN_D1_DATABASE_ID);

	return {
		appEnv: clean(env.MAIL_BIN_APP_ENV),
		appName: clean(env.MAIL_BIN_APP_NAME),
		compatibilityDate: clean(env.MAIL_BIN_COMPATIBILITY_DATE),
		databaseId,
		databaseName: clean(env.MAIL_BIN_D1_DATABASE_NAME),
		outFile: clean(env.WRANGLER_CONFIG),
		previewDatabaseId: clean(env.MAIL_BIN_D1_PREVIEW_DATABASE_ID),
		previewUrls: readBoolean(env.MAIL_BIN_PREVIEW_URLS, false),
		workerName: clean(env.MAIL_BIN_WORKER_NAME),
		workersDev: readBoolean(env.MAIL_BIN_WORKERS_DEV, true),
	};
}

function buildWranglerConfig(options: WranglerConfigOptions = {}) {
	const workerName = options.workerName ?? "mail-bin";
	const databaseName = options.databaseName ?? workerName;
	const d1Database: Record<string, string> = {
		binding: "DB",
		database_name: databaseName,
		migrations_dir: "./drizzle",
	};

	if (options.databaseId) {
		d1Database.database_id = options.databaseId;
	}

	if (options.previewDatabaseId) {
		d1Database.preview_database_id = options.previewDatabaseId;
	}

	return {
		$schema: "node_modules/wrangler/config-schema.json",
		name: workerName,
		main: "./src/index.ts",
		compatibility_date: options.compatibilityDate ?? "2026-04-19",
		compatibility_flags: ["nodejs_compat"],
		workers_dev: options.workersDev ?? true,
		preview_urls: options.previewUrls ?? false,
		assets: {
			directory: "./dist/client/client",
			not_found_handling: "single-page-application",
		},
		d1_databases: [d1Database],
		vars: {
			APP_NAME: options.appName ?? "Mail Bin",
			APP_ENV: options.appEnv ?? "production",
		},
		observability: {
			enabled: true,
		},
	};
}

function formatWranglerConfig(config: ReturnType<typeof buildWranglerConfig>) {
	return `/**\n * Generated by scripts/write-wrangler-config.ts.\n * Do not commit account-specific generated configs.\n */\n${JSON.stringify(config, null, "\t")}\n`;
}

export async function writeWranglerConfig(options: WranglerConfigOptions = {}) {
	const workerName = options.workerName ?? "mail-bin";
	const databaseName = options.databaseName ?? workerName;
	const outFile = options.outFile ?? generatedWranglerConfigPath;
	const absoluteOutFile = resolve(process.cwd(), outFile);
	await mkdir(dirname(absoluteOutFile), { recursive: true });
	await writeFile(absoluteOutFile, formatWranglerConfig(buildWranglerConfig(options)));

	return {
		databaseId: options.databaseId,
		databaseName,
		outFile,
		workerName,
	};
}
